---
title: "OI perception data explore"
author: "Louise Shepperd"
date: "`r Sys.Date()`"
output:   
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(dplyr)
library(ggplot2)
library(knitr)
library(papaja)
library(htmlTable)
library(magrittr)
library(Gmisc)
library(patchwork)
library(corrplot)
library(forcats)
library(vtable)

theme_set(theme_apa())

# colour palettes for plots http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

### Introduction

This document offers an exploratory overview of quantitative data from the debrief questionnaire for the two language groups.This will also be explored in relation to participant demographic information and performance on the audiovisual matching task.

The research questions are as follows:

***RQ 2: What influence of written input are learners aware of regarding word learning?***

*2.1: What was the perceived influence of written input on their learning in the study?*  

*2.2: What were participants' beliefs around the importance of written input when learning new words more broadly?*

This document will explore each of these questions in turn.

### RQ 2.1  Perception of OI influence in the study




### RQ 2.2  Perception of OI influence in general



